### ISSUE TITLE
> 🚀  Engine ready. Serving Python 3.7.0.

### ISSUE THREAD

**Issue by Nuckijfuta** [taitems/iOS-Overlay#18]
> 🚀  Engine ready. Serving Python 3.7.0.
> 👌  Ready for backtesting.
> ✅  Starting backtest, using data from 17.04.2021-00:00:00 until 20.04.2021-00:00:00 with Custom Scenario (Fees 0.1%, Starting Balance: 1,000 USDT)
17.04.2021-00:00:00> Traceback (most recent call last):
17.04.2021-00:00:00>   File "bot.py", line 66, in handler
17.04.2021-00:00:00> TypeError
17.04.2021-00:00:00> :
17.04.2021-00:00:00> unsupported operand type(s) for *: 'float' and 'trality.data.data.TralityData'

__Originally posted by @ceyhanmolla in https://github.com/ffavero/trality_code/issues/1__

**Comment by Nuckijfuta** [comment]
> > 🚀  Engine ready. Serving Python 3.7.0.
> 
> > 👌  Ready for backtesting.
> 
> > ✅  Starting backtest, using data from 17.04.2021-00:00:00 until 20.04.2021-00:00:00 with Custom Scenario (Fees 0.1%, Starting Balance: 1,000 USDT)
> 
> 17.04.2021-00:00:00> Traceback (most recent call last):
> 
> 17.04.2021-00:00:00>   File "bot.py", line 66, in handler
> 
> 17.04.2021-00:00:00> TypeError
> 
> 17.04.2021-00:00:00> :
> 
> 17.04.2021-00:00:00> unsupported operand type(s) for *: 'float' and 'trality.data.data.TralityData'
> 
> 
> 
> 
> 
> __Originally posted by @ceyhanmolla in https://github.com/ffavero/trality_code/issues/1__

#[@
]()
